import { expect, test } from "@playwright/test";

/**
 * FRD-02 REQ-02-014 — the accessible empty-column marker, verified in a REAL browser (reviewer,
 * builder-blind, DR-080). jsdom can only see the `sr-only` CLASS; it cannot prove the utility is
 * actually generated by Tailwind and hides the text. Here, against the deterministic e2e fixture
 * (`e2e/server-env.json`), every board column whose count reads 0 must expose exactly one
 * `role="status"` "Sin ideas en esta columna" marker that is VISUALLY hidden (the empty column's
 * look is unchanged: only the decorative dash shows), and every populated column exposes none.
 *
 * Viewport-agnostic by construction (BL-0001): it asserts DOM/ARIA facts and the marker's own
 * box size, never on-screen visibility of a column, so it holds on the desktop AND mobile
 * projects (columns scroll horizontally on mobile but stay rendered).
 */

const EMPTY_TEXT = "Sin ideas en esta columna";
const COLUMNS = ["discovered", "documented", "design", "architecture", "building", "shipped"];

test("board · empty columns expose a visually-hidden status marker; populated columns none", async ({
  page,
}) => {
  const res = await page.goto("/board", { waitUntil: "domcontentloaded" });
  expect(res?.status()).toBeLessThan(400);
  await expect(page.getByTestId("board-scroll-container")).toBeAttached();

  let emptyColumns = 0;
  for (const id of COLUMNS) {
    const column = page.getByTestId(`board-column-${id}`);
    await expect(column).toBeAttached();
    const count = Number((await column.locator("header span").first().innerText()).trim());
    const markers = column.getByRole("status", { name: EMPTY_TEXT });

    if (count > 0) {
      await expect(markers).toHaveCount(0);
      continue;
    }

    emptyColumns += 1;
    await expect(markers).toHaveCount(1);
    await expect(markers).toHaveText(EMPTY_TEXT);

    // Visually hidden for real (Tailwind's sr-only generated + applied): a ≤1px clipped box.
    const box = await markers.boundingBox();
    expect(box, `${id}: status marker must be laid out (in the a11y tree)`).not.toBeNull();
    expect(box?.width ?? 99).toBeLessThanOrEqual(1);
    expect(box?.height ?? 99).toBeLessThanOrEqual(1);

    // The decorative dash still renders and stays out of the accessibility tree.
    const dash = column.getByText("—", { exact: true });
    await expect(dash).toBeVisible();
    await expect(dash).toHaveAttribute("aria-hidden", "true");
  }

  // The fixture board has populated AND empty columns; the check must never pass vacuously.
  expect(emptyColumns).toBeGreaterThan(0);
  expect(emptyColumns).toBeLessThan(COLUMNS.length);
});
