/**
 * WO-05-006 — WorkOrderEmpty (CMP-05-empty) tests
 *
 * RED phase — written before implementation.
 *
 * Traceability:
 *   AC-05-006.1  WHEN a project has no work orders, the view SHALL show a message
 *               that they are generated in /pandacorp:blueprint.
 *
 * Stack: Vitest + @testing-library/react + jsdom.
 */

import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { WorkOrderEmpty } from "../wo-empty";

// ---------------------------------------------------------------------------
// AC-05-006.1 — empty state message
// ---------------------------------------------------------------------------

describe("frd-05: AC-05-006.1 — WorkOrderEmpty renders the empty state", () => {
  it("frd-05: AC-05-006.1 — WHEN rendered THEN the empty container is present", () => {
    render(<WorkOrderEmpty />);
    expect(screen.getByTestId("wo-empty")).toBeDefined();
  });

  it("frd-05: AC-05-006.1 — WHEN rendered THEN message references /pandacorp:blueprint", () => {
    render(<WorkOrderEmpty />);
    const el = screen.getByTestId("wo-empty");
    expect(el.textContent).toContain("/pandacorp:blueprint");
  });

  it("frd-05: AC-05-006.1 — WHEN rendered THEN message explains work orders are generated by blueprint", () => {
    render(<WorkOrderEmpty />);
    const el = screen.getByTestId("wo-empty");
    // Must communicate that work orders come from blueprint (AC-05-006.1 copy)
    expect(el.textContent?.length).toBeGreaterThan(20);
  });

  it("frd-05: AC-05-006.1 — WHEN rendered THEN has a copy button for /pandacorp:blueprint", () => {
    render(<WorkOrderEmpty />);
    // The copy button component renders with data-testid=copy-button (CMP-02)
    expect(screen.getByTestId("copy-button")).toBeDefined();
  });

  it("frd-05: AC-05-006.1 — WHEN rendered THEN the empty state has role=status for a11y", () => {
    render(<WorkOrderEmpty />);
    const el = screen.getByTestId("wo-empty");
    expect(el.getAttribute("role")).toBe("status");
  });
});
