/**
 * WO-05-006 — WorkOrderEmpty (CMP-05-empty)
 *
 * Server Component. Shown when listWorkOrders returns [] — the project has
 * no work orders yet (generated by /pandacorp:architecture).
 *
 * Traceability:
 *   AC-05-006.1  WHEN a project has no work orders, the view SHALL show a message
 *               that they are generated in /pandacorp:architecture.
 *
 * Design rules:
 *   - ZERO hardcoded colors — CSS custom properties only.
 *   - data-testid on every significant element.
 *   - role=status for a11y (screen-reader friendly empty state).
 *   - Reuses CMP-02 CopyButton for the /pandacorp:architecture command.
 */

import { CopyButton } from "@/components/core/CopyButton/CopyButton";

const ARCHITECTURE_CMD = "/pandacorp:architecture";

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const CONTAINER_STYLE: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  gap: "calc(var(--spacing, 0.25rem) * 4)",
  padding: "calc(var(--spacing, 0.25rem) * 16)",
  textAlign: "center",
  color: "var(--color-text-muted, currentColor)",
  height: "100%",
  minHeight: "240px",
};

const ICON_STYLE: React.CSSProperties = {
  fontSize: "2.5rem",
  lineHeight: 1,
  opacity: 0.4,
};

const HEADING_STYLE: React.CSSProperties = {
  fontSize: "1rem",
  fontWeight: 600,
  color: "var(--color-text, currentColor)",
  margin: 0,
};

const BODY_STYLE: React.CSSProperties = {
  fontSize: "0.875rem",
  lineHeight: 1.6,
  margin: 0,
  maxWidth: "42ch",
  opacity: 0.75,
};

const CMD_STYLE: React.CSSProperties = {
  fontFamily: "var(--font-mono, ui-monospace, monospace)",
  fontSize: "0.875rem",
  background: "var(--color-code-bg, var(--color-surface-raised, Canvas))",
  border: "var(--hairline, 1px) solid var(--color-border, currentColor)",
  borderRadius: "var(--radius, 6px)",
  padding: "2px calc(var(--spacing, 0.25rem) * 2)",
  color: "var(--color-accent, var(--color-text, currentColor))",
};

const ACTION_ROW_STYLE: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: "calc(var(--spacing, 0.25rem) * 2)",
};

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * WorkOrderEmpty — displayed when the project has no work orders yet.
 *
 * Server Component (CopyButton is "use client" — it hydrates on the client).
 * AC-05-006.1.
 */
export function WorkOrderEmpty(): React.JSX.Element {
  return (
    <div
      data-testid="wo-empty"
      role="status"
      aria-label="Sin work orders — generados por /pandacorp:architecture"
      style={CONTAINER_STYLE}
    >
      <span aria-hidden="true" style={ICON_STYLE}>
        📋
      </span>
      <h3 style={HEADING_STYLE}>Sin work orders todavía</h3>
      <p style={BODY_STYLE}>
        Los work orders se generan al ejecutar <code style={CMD_STYLE}>{ARCHITECTURE_CMD}</code> en
        este proyecto. Aparecerán aquí con su estado actualizado en tiempo real.
      </p>
      <div style={ACTION_ROW_STYLE}>
        <span style={{ fontSize: "0.8125rem", opacity: 0.7 }}>Copiar comando:</span>
        <CopyButton value={ARCHITECTURE_CMD} label={ARCHITECTURE_CMD} />
      </div>
    </div>
  );
}
