import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { readFileSync } from "node:fs";
import { lstat, mkdir, readFile, realpath, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const canonical = (project) => path.join(project, ".pandacorp/run/codex-attended-permit.json");
const atomic = async (file, value) => { const tmp = `${file}.tmp-${process.pid}-${randomBytes(6).toString("hex")}`; await writeFile(tmp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 }); await rename(tmp, file); };
const macBody = (value) => JSON.stringify(Object.fromEntries(Object.entries(value).filter(([key]) => key !== "mac").sort(([a],[b]) => a.localeCompare(b))));
const seal = (value, secret) => ({ ...value, mac: createHmac("sha256", secret).update(macBody(value)).digest("hex") });
const validMac = (value, secret) => { if (!/^[0-9a-f]{64}$/.test(value.mac || "") || !secret) return false; const expected = createHmac("sha256", secret).update(macBody(value)).digest(); return timingSafeEqual(Buffer.from(value.mac, "hex"), expected); };
const exact = (permit, expected) => permit.run_id === expected.runId && permit.change === expected.change && permit.frds === expected.frds && permit.max_spend === expected.maxSpend && permit.max_duration === expected.maxDuration && permit.max_retries === expected.maxRetries && permit.max_blocks === expected.maxBlocks;
async function readCanonical(project, supplied) { const file = path.resolve(supplied); const expected = canonical(project); if (file !== expected) throw Object.assign(new Error("attended permit path is not canonical"), { code: "PROFILE" }); const [entry, actual, root] = await Promise.all([lstat(file), realpath(file), realpath(path.dirname(file))]); if (!entry.isFile() || entry.isSymbolicLink() || actual !== path.join(root, path.basename(file))) throw Object.assign(new Error("attended permit must be a real project-local file"), { code: "PROFILE" }); return { file, permit: JSON.parse(await readFile(file, "utf8")) }; }
async function issueAttendedPermit(project, expected, secret, launcherPid = process.pid) { if (!secret || (!expected.change && !/^frd-[a-z0-9-]+$/.test(expected.frds)) || (expected.change && (expected.frds || !/^[a-z0-9-]+$/.test(expected.change)))) throw Object.assign(new Error("attended permit requires exactly one target and an inherited secret"), { code: "PROFILE" }); await mkdir(path.dirname(canonical(project)), { recursive: true }); const value = { schema: 1, kind: "pandacorp-codex-attended-permit", status: "issued", execution_profile: "attended_foreground", launcher_pid: Number(launcherPid), nonce: randomBytes(32).toString("hex"), issued_at: new Date().toISOString(), ...{ run_id: expected.runId, change: expected.change, frds: expected.frds, max_spend: expected.maxSpend, max_duration: expected.maxDuration, max_retries: expected.maxRetries, max_blocks: expected.maxBlocks } }; await atomic(canonical(project), seal(value, secret)); return { path: canonical(project) };
}
export async function consumeBySupervisor(project, supplied, expected, launcherSecret) { const { file, permit } = await readCanonical(project, supplied); if (permit.kind !== "pandacorp-codex-attended-permit" || permit.status !== "issued" || permit.launcher_pid !== process.ppid || !exact(permit, expected) || !validMac(permit, launcherSecret)) throw Object.assign(new Error("invalid or replayed attended supervisor permit"), { code: "PROFILE" }); const executorSecret = randomBytes(32).toString("hex"); const { mac: _old, ...unsigned } = permit; const next = seal({ ...unsigned, status: "executor_issued", supervisor_pid: process.pid, supervisor_consumed_at: new Date().toISOString() }, executorSecret); await atomic(file, next); return { permit: next, executorSecret }; }
export async function consumeByExecutor(project, supplied, expected, executorSecret) { const { file, permit } = await readCanonical(project, supplied); if (permit.kind !== "pandacorp-codex-attended-permit" || permit.status !== "executor_issued" || permit.supervisor_pid !== process.ppid || !exact(permit, expected) || !validMac(permit, executorSecret)) throw Object.assign(new Error("invalid or replayed attended executor permit"), { code: "PROFILE" }); const { mac: _old, ...unsigned } = permit; const next = { ...unsigned, status: "consumed", executor_pid: process.pid, consumed_at: new Date().toISOString() }; await atomic(file, next); return next; }
export async function terminalAttendedPermit(project, supplied, reason) { const { file, permit } = await readCanonical(project, supplied); if (!new Set(["issued", "executor_issued", "consumed"]).has(permit.status)) return permit; const next = { ...permit, status: "terminal", terminal_reason: reason, terminal_at: new Date().toISOString() }; await atomic(file, next); return next; }

const invokedAsCli = process.argv[1] && await realpath(process.argv[1]).catch(() => "") === await realpath(fileURLToPath(import.meta.url)).catch(() => "");
if (invokedAsCli) {
  const take = (name) => { const i = process.argv.indexOf(`--${name}`); return i < 0 ? "" : process.argv[i + 1] || ""; }; const mode = take("mode"); const project = await realpath(path.resolve(take("project") || "."));
  const expected = { runId: take("run-id"), change: take("change"), frds: take("frds"), maxSpend: Number(take("max-spend")), maxDuration: Number(take("max-duration")), maxRetries: Number(take("max-retries")), maxBlocks: Number(take("max-blocks")) };
  if (mode === "issue") { const launcherPid=Number(take("launcher-pid")); const { execFileSync }=await import("node:child_process"); const ps=(pid,field)=>execFileSync("ps",["-p",String(pid),"-o",`${field}=`],{encoding:"utf8"}).trim(); const expectedLauncher=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../scripts/launch-codex-implement.sh"),canonicalLauncher=await realpath(expectedLauncher); const command=ps(launcherPid,"command"); let commandCanonical=false;for(const token of command.split(/\s+/)){if(!token.endsWith("launch-codex-implement.sh"))continue;if(await realpath(token).catch(()=>"")===canonicalLauncher){commandCanonical=true;break;}}let cursor=process.ppid,ancestor=false;for(let i=0;i<8&&cursor>1;i++){if(cursor===launcherPid){ancestor=true;break;}cursor=Number(ps(cursor,"ppid"));} if (!Number.isSafeInteger(launcherPid)||launcherPid<1||!ancestor||!commandCanonical) throw new Error("attended permit issuance is launcher-only"); const fd=Number(take("secret-fd")||0); const secret=readFileSync(fd,"utf8").trim(); process.stdout.write(`${JSON.stringify(await issueAttendedPermit(project, expected, secret, launcherPid))}\n`); } else if (mode === "terminal") process.stdout.write(`${JSON.stringify(await terminalAttendedPermit(project, take("permit"), take("reason") || "launcher-exit"))}\n`); else throw new Error("unsupported attended permit mode");
}
