# AGENTS.md — {{PROJECT_NAME}}

Standards for any AI agent working on this project. It is the source of truth for conventions, aligned with the Pandacorp factory standards. (Claude Code reads `CLAUDE.md`, which imports this file.)

## Priority order
User request → this AGENTS.md → the project's **engineering rules** (`docs/rules/`) → the project documents in `docs/` → language defaults.

## Engineering rules (mandatory) — `docs/rules/`
This project's engineering rules live in **`docs/rules/`**, split by purpose and technology and indexed by `docs/rules/README.md`. **Read them before writing or changing code, and follow them** (they are not optional reading). Only the rules that apply to THIS project are present: the general best-practice files (always) plus the tech-specific ones for the chosen stack. They are the operative, portable form of the Pandacorp factory standards and hold **whether or not** this project is built with Pandacorp. If a situation isn't covered there, follow the spirit of those rules; for recurring decisions consult the factory's decision registry.

## Language & interaction
Git-tracked status decides the language: committed → English (code: variables, functions, types, comments, commits; and product/technical docs); gitignored → Spanish (the owner-facing communication layer + personal data). User-facing content via i18n (never hardcoded), default locale from the product's launch-language decision. **The interaction with the owner is always in Spanish** — everything the agent says in chat and inside any skill (questions, explanations, progress, recommendations) is in Spanish, regardless of the artifact's language.

**Interaction style (DR-110, scope: the lead agent's owner-facing replies only — NOT product/UI copy, NOT orchestrator↔subagent communication).** Mark where the real answer begins after any progress narration (`---` + a short bold label). Default concise, scannable, and high-level — headers/bold/bullets over walls of text, technical depth only on request or when the topic demands precision (security, money, data loss, irreversible actions). Prefer storytelling/analogies over jargon; visualize a complex flow or algorithm with a diagram/widget instead of describing it in prose. Red-team a proposal that requires judgment before agreeing — never rubber-stamp — but skip that for simple statements/questions/greetings. Full rule: `factory/standards/conventions.md` (CONV-11).

**Evidence before assertion (CONV-13, scope: every factual claim to the owner about the state of code/data/systems).** No fact is asserted from conversation context, training memory or a recorded flag: anchor it to an in-session tool observation (a file read, a command's output, a live query); re-verify recorded state and subagent reports against live signals before repeating them; say "not verified" when it isn't. Full rule: `factory/standards/conventions.md` (CONV-13).

**Subagent model selection (DR-111, scope: ad-hoc delegation only — NOT Pandacorp's own named agents, which already pin their `model:` in frontmatter, NOT the build engine's own escalation, DR-073/DR-108).** When delegating to a subagent (the `Agent` tool, or a `Workflow`'s `agent()`) without an explicit model, calculate the tier from the SUBTASK's complexity — never default to the parent conversation's own tier: haiku for mechanical/zero-judgment work, sonnet as the default floor for real work, opus for genuine judgment/high complexity. Escalate upward, never downward, if a lower tier proves inadequate. Fable is NEVER chosen automatically — only on the owner's explicit request, or after asking for confirmation first. Full rule: `factory/standards/conventions.md` (CONV-12).

## Changes through skills (write-gate)
WITH the pandacorp plugin, changes that touch app behavior, a canonical doc (PRD/FRD/blueprint/ADR/DESIGN) or state (`.pandacorp/status.yaml`, work-orders) flow through the `/pandacorp:*` skills — the *assisted* path that keeps the two layers, status, work-orders, TDD and review honest. Exempt (do directly): reading/debugging and micro non-product edits (a typo, local config, a throwaway experiment). When the owner asks for a change, auto-invoke the right skill, announcing it (any feature/change/bug → **`change`**, the single front door (DR-069) — it classifies and queues it; never route the owner to `iterate`/`bug` directly, they are its internal engines; a decision → `decide`; big package → `new-version`); auto-invoking enters the skill only — its internal human-gates (production, money, delete, external comms) still ask. WITHOUT the plugin (a fork/clone of just this repo) the skills aren't available — apply the same discipline by hand: when you change behavior, update the matching FRD + `docs/decision-log.md`. Detail in `.pandacorp/guide.md`.

## This project's stack
Defined in `docs/product/architecture.md` (the platform architecture, chosen and approved in the architecture phase). See concrete versions and services there; per-feature implementation design lives in each `docs/frds/frd-NN-<slug>/blueprint.md`.

## Other runtimes (Codex, Cursor, OpenCode…)

This file is the canonical instruction set for ANY coding agent. Claude Code reads it through `CLAUDE.md`'s import and adds the `/pandacorp:*` skills; Codex, Cursor and OpenCode read it natively. If you are NOT Claude Code:

- The factory (skills, standards, decision registry) lives at the path stamped in `.pandacorp/guide.md`. To run a lifecycle phase, read `<factory>/plugin/skills/<slug>/SKILL.md` and follow it, applying the runtime translation rules in `<factory>/factory/standards/agent-portability.md` (tool equivalences, model tiers, degradation).
- Codex may write normal project build state only through PORT-5's exact promoted `EXPERIMENTAL/attended_foreground/targeted-only` profile: one FRD or one ready change, foreground, cumulative duration `<=7200`, zero automatic restarts, ending in `implementation`. Bare/global, multiple-FRD, background/unattended/overnight, hardening/release and cross-runtime switching remain denied while their R10/R11 gates are pending. Every other non-Claude runtime remains READ/REVIEW-ONLY until separately promoted. Runtime execution is strict-local, never live takeover or simultaneous build. See PORT-5 in the factory standard.
- The change queue (`.pandacorp/inbox/changes/`) and the decisions inbox are plain files: any runtime files changes by following their templates — never edit product behavior ad hoc.
- Every rule in this file (language, gates, documentation discipline) is runtime-independent and never degrades.
