/**
 * lib/gamification.ts — Pure XP / level / celebration engine (FRD-09)
 *
 * Platform golden rule (architecture §1): read-only derivation only. Pure functions.
 * This module is flagged as a NEW file in blueprint §7.
 *
 * Interfaces implemented (blueprint §3):
 *   IF-09-guild-xp  — computeGuildLevel(outcomes): GuildLevel
 *   IF-09-celebration — classifyCelebration(event): CelebrationTier
 *
 * Traceability:
 *   AC-09-001.1 — computeGuildLevel returns { level, title, xp, next, pctToNext }
 *   AC-09-001.2 — XP only from verifiable results (WO closed, phase, release, green tests)
 *   AC-09-001.3 — No outcomes → honest zero state; never bar stuck at ~80%
 *   AC-09-001.4 — Streak is weekly (with freeze cap), never daily-reset
 *   AC-09-001.5 — Pure function, fixture-tested
 *   AC-09-005.1 — maps outcome events to the correct celebration tier
 *   AC-09-005.2 — non-result/activity events → "none" (ethical constraint: no XP for activity)
 *   AC-09-005.3 — ambiguous/unknown → "none" (never a default celebration); pure function
 *
 * FRD-09 non-negotiable design constraints enforced here:
 *   - XP / celebrations ONLY for verifiable results (WO closed, phase done, release, level-up).
 *   - NO XP for: app-open, read, write, edit, message, navigation, activity.
 *   - NO celebration for: activity events, failure, ambiguous.
 *   - Celebrations SCALE: toast (WO) → phase → release → levelup. Never flat.
 *   - Forbidden patterns: leaderboards, lives, daily-reset streaks, false urgency, bar at ~80%.
 */
import type { Event, EventsSnapshot } from "../events/events";
import type { StatusResult } from "../status/status";

// ---------------------------------------------------------------------------
// IF-09-guild-xp — computeGuildLevel (WO-09-001)
// ---------------------------------------------------------------------------

/**
 * Rank entry in the guild XP ladder.
 *
 * `threshold` is the minimum XP required to hold this rank.
 * The first rank always has threshold = 0 (no XP required).
 * Thresholds must be strictly increasing.
 */
export type Rank = {
  /** Display name (Spanish). */
  readonly title: string;
  /** English name (for the Rangos ladder / reference). */
  readonly titleEn: string;
  /** Tabler icon class for the rank (fallback when the sprite is unavailable). */
  readonly icon: string;
  /** Rank-family sprite slug → /ranks/<sprite>.png (custom pixel-art emblem). */
  readonly sprite: string;
  /** Minimum (entry) granular LEVEL for this rank — a rank spans a band of levels. */
  readonly minLevel: number;
  /** Sub-grade within the family: 1/2/3 (I·II·III), or 0 for none (Humano + tops). */
  readonly grade: number;
};

/**
 * The 40-rank guild ladder (RPG / Final Fantasy tone, owner-authored 2026-06-25).
 *
 * The guild level IS the rank index (1 rank per level): level 1 = Humano, … ,
 * level 40 = Portador del Juramento Eterno. Families climb in three grades (I·II·III).
 * Names + icons here; XP thresholds are generated by `rankThreshold` (a smooth
 * super-linear curve — the top is deliberately FAR so the climb feels aspirational).
 *
 * XP weights (per outcome, §2 honesty contract): WO 10 · phase 50 · release 200 ·
 * green test 1 · weekly streak 5/wk (capped). Activity is NEVER rewarded.
 */
const RANK_DEFS: ReadonlyArray<{ es: string; en: string; icon: string }> = [
  { es: "Humano", en: "Human", icon: "ti-user" },
  { es: "Buscador del Alba I", en: "Dawn Seeker I", icon: "ti-sunrise" },
  { es: "Buscador del Alba II", en: "Dawn Seeker II", icon: "ti-sunrise" },
  { es: "Buscador del Alba III", en: "Dawn Seeker III", icon: "ti-sunrise" },
  { es: "Portador de Luz I", en: "Lightbearer I", icon: "ti-flame" },
  { es: "Portador de Luz II", en: "Lightbearer II", icon: "ti-flame" },
  { es: "Portador de Luz III", en: "Lightbearer III", icon: "ti-flame" },
  { es: "Guardián del Juramento I", en: "Oathkeeper I", icon: "ti-shield" },
  { es: "Guardián del Juramento II", en: "Oathkeeper II", icon: "ti-shield" },
  { es: "Guardián del Juramento III", en: "Oathkeeper III", icon: "ti-shield" },
  { es: "Guardián de Glifos I", en: "Glyphwarden I", icon: "ti-hexagon" },
  { es: "Guardián de Glifos II", en: "Glyphwarden II", icon: "ti-hexagon" },
  { es: "Guardián de Glifos III", en: "Glyphwarden III", icon: "ti-hexagon" },
  { es: "Guardián del Éter I", en: "Aether Warden I", icon: "ti-sparkles" },
  { es: "Guardián del Éter II", en: "Aether Warden II", icon: "ti-sparkles" },
  { es: "Guardián del Éter III", en: "Aether Warden III", icon: "ti-sparkles" },
  { es: "Portador de Esquirla I", en: "Shardbearer I", icon: "ti-diamond" },
  { es: "Portador de Esquirla II", en: "Shardbearer II", icon: "ti-diamond" },
  { es: "Portador de Esquirla III", en: "Shardbearer III", icon: "ti-diamond" },
  { es: "Caballero Radiante I", en: "Knight Radiant I", icon: "ti-sword" },
  { es: "Caballero Radiante II", en: "Knight Radiant II", icon: "ti-sword" },
  { es: "Caballero Radiante III", en: "Knight Radiant III", icon: "ti-sword" },
  { es: "Invocador de Reinos I", en: "Realmcaller I", icon: "ti-world" },
  { es: "Invocador de Reinos II", en: "Realmcaller II", icon: "ti-world" },
  { es: "Invocador de Reinos III", en: "Realmcaller III", icon: "ti-world" },
  { es: "Heraldo del Alba I", en: "Dawn Herald I", icon: "ti-flare" },
  { es: "Heraldo del Alba II", en: "Dawn Herald II", icon: "ti-flare" },
  { es: "Heraldo del Alba III", en: "Dawn Herald III", icon: "ti-flare" },
  { es: "Señor de Tormentas I", en: "Stormlord I", icon: "ti-bolt" },
  { es: "Señor de Tormentas II", en: "Stormlord II", icon: "ti-bolt" },
  { es: "Señor de Tormentas III", en: "Stormlord III", icon: "ti-bolt" },
  { es: "Ascendente I", en: "Ascendant I", icon: "ti-arrow-big-up-lines" },
  { es: "Ascendente II", en: "Ascendant II", icon: "ti-arrow-big-up-lines" },
  { es: "Ascendente III", en: "Ascendant III", icon: "ti-arrow-big-up-lines" },
  { es: "Ascendente del Fénix", en: "Phoenix Ascendant", icon: "ti-flame" },
  { es: "Señor del Leviatán", en: "Leviathan Lord", icon: "ti-ripple" },
  { es: "Señor Dragón Carmesí", en: "Crimson Dragonlord", icon: "ti-meteor" },
  { es: "Guardián Celestial", en: "Celestial Warden", icon: "ti-star" },
  { es: "Soberano del Alba", en: "Dawn Sovereign", icon: "ti-crown" },
  { es: "Portador del Juramento Eterno", en: "Eternal Oathbearer", icon: "ti-trophy" },
];

/**
 * XP needed to REACH a given granular level (1-based). Level 1 = 0 XP; the curve
 * is super-linear (rounded to nearest 5) so each level costs more than the last —
 * leveling gets harder the higher you climb.
 */
export function xpForLevel(level: number): number {
  if (level <= 1) return 0;
  return Math.round((8 * (level - 1) ** 1.85) / 5) * 5;
}

/** The granular level for an XP total (1-based, monotonic, effectively unbounded). */
function levelForXp(xp: number): number {
  let level = 1;
  while (level < 999 && xpForLevel(level + 1) <= xp) level++;
  return level;
}

/**
 * Band size (number of levels) for rank index i — widens toward the summit so the
 * higher ranks take more levels to earn (the climb gets harder). 3,3,3,3,4,4,…
 */
function rankBandSize(i: number): number {
  return 3 + Math.floor(i / 4);
}

/** The minimum (entry) level for each rank, cumulative from `rankBandSize`. */
const RANK_MIN_LEVEL: readonly number[] = (() => {
  const out: number[] = [];
  let lvl = 1;
  for (let i = 0; i < RANK_DEFS.length; i++) {
    out.push(lvl);
    lvl += rankBandSize(i);
  }
  return out;
})();

/** Sub-grade (1/2/3) from a rank's roman-numeral suffix; 0 when none. */
function rankGrade(title: string): number {
  if (title.endsWith(" III")) return 3;
  if (title.endsWith(" II")) return 2;
  if (title.endsWith(" I")) return 1;
  return 0;
}

/**
 * Rank-family sprite slug per level (1-based), → /ranks/<slug>.png. Each I·II·III
 * family shares one emblem; the 6 standalone tops + Humano each have their own.
 * 1 + 11×3 + 6 = 40.
 */
const RANK_SPRITES: readonly string[] = [
  "human",
  "dawn-seeker",
  "dawn-seeker",
  "dawn-seeker",
  "lightbearer",
  "lightbearer",
  "lightbearer",
  "oathkeeper",
  "oathkeeper",
  "oathkeeper",
  "glyphwarden",
  "glyphwarden",
  "glyphwarden",
  "aether-warden",
  "aether-warden",
  "aether-warden",
  "shardbearer",
  "shardbearer",
  "shardbearer",
  "knight-radiant",
  "knight-radiant",
  "knight-radiant",
  "realmcaller",
  "realmcaller",
  "realmcaller",
  "dawn-herald",
  "dawn-herald",
  "dawn-herald",
  "stormlord",
  "stormlord",
  "stormlord",
  "ascendant",
  "ascendant",
  "ascendant",
  "phoenix-ascendant",
  "leviathan-lord",
  "crimson-dragonlord",
  "celestial-warden",
  "dawn-sovereign",
  "eternal-oathbearer",
];

/** The guild rank ladder — each rank is a BAND of granular levels (not 1:1). */
export const RANKS: readonly Rank[] = RANK_DEFS.map((d, i) => ({
  title: d.es,
  titleEn: d.en,
  icon: d.icon,
  sprite: RANK_SPRITES[i] ?? "human",
  minLevel: RANK_MIN_LEVEL[i] ?? 1,
  grade: rankGrade(d.es),
}));

/** The rank index whose level-band contains the given granular level (0-based). */
export function rankForLevel(level: number): number {
  let idx = 0;
  for (let i = 0; i < RANKS.length; i++) {
    if (level >= (RANKS[i]?.minLevel ?? 1)) idx = i;
  }
  return idx;
}

/** Maximum weekly streak weeks counted (freeze concept — no unbounded multiplier). */
const MAX_STREAK_WEEKS = 52;

/** XP earned per closed work order. */
const XP_PER_WO = 10;

/** XP earned per completed phase. */
const XP_PER_PHASE = 50;

/** XP earned per release / launch (reaching the launched "release" phase). */
const XP_PER_RELEASE = 200;

/** XP earned per green test run (minor confirmation signal). */
const XP_PER_GREEN_TEST = 1;

/** XP earned per week of weekly streak (capped at MAX_STREAK_WEEKS). */
const XP_PER_STREAK_WEEK = 5;

/**
 * The verifiable outcomes that drive guild XP.
 *
 * Each field maps to a source from the honesty contract (blueprint §2):
 *   - `workOrdersDone`  ← `status.yaml:work_orders_done` / `achievement` event with workOrder
 *   - `phasesCompleted` ← `status.yaml:phase` transitions
 *   - `releases`        ← `phase: release` reached in portfolio
 *   - `greenTestRuns`   ← `test_ok` events
 *   - `weeklyStreak`    ← optional; weekly cadence with freeze (never daily-reset)
 *
 * Deliberately ABSENT from this type (FRD-09 ethical constraint):
 *   - No `appOpens`, `navigations`, `pageViews` — activity is NOT rewarded.
 *   - No `dailyStreak` — only `weeklyStreak` with freeze.
 */
export type GuildOutcomes = {
  /** Number of work orders closed green. */
  readonly workOrdersDone: number;
  /** Number of phases completed (design, architecture, implementation, release). */
  readonly phasesCompleted: number;
  /** Number of releases (projects reaching the launched "release" phase). */
  readonly releases: number;
  /** Number of green test suite runs. */
  readonly greenTestRuns: number;
  /**
   * Current weekly streak (weeks with at least one closed WO).
   * Optional — omit or set to 0 for no streak bonus.
   * Capped at MAX_STREAK_WEEKS (freeze concept).
   */
  readonly weeklyStreak?: number;
};

/**
 * The computed guild level result.
 *
 * All fields are derived purely from GuildOutcomes — no I/O, no clock, no engagement bonus.
 */
export type GuildLevel = {
  /** Granular guild level (1+), derived from XP — climbs faster than the rank. */
  readonly level: number;
  /** Current rank index in RANKS (0-based; a rank spans a band of levels). */
  readonly rankIndex?: number;
  /** Human-readable rank title (Spanish) from the RANKS ladder. */
  readonly title: string;
  /**
   * English rank name + Tabler icon for the current rank. Always set by
   * computeGuildLevel; optional so hand-built test fixtures stay terse.
   */
  readonly titleEn?: string;
  readonly icon?: string;
  /** Rank-family sprite slug → /ranks/<slug>.png. */
  readonly sprite?: string;
  /** Current rank's sub-grade: 1/2/3 (I·II·III), 0 = none. */
  readonly grade?: number;
  /** Total accumulated XP (sum of all verifiable outcomes). */
  readonly xp: number;
  /** XP required to reach the NEXT granular level. */
  readonly next: number;
  /**
   * Percentage progress toward the next LEVEL, 0–100.
   * Exactly 0 when xp = 0 (honest zero state — never near 80% with no real work).
   */
  readonly pctToNext: number;
};

/**
 * Compute the guild's current level, title, XP, next threshold and progress bar
 * from a set of verifiable real outcomes (WO-09-001, IF-09-guild-xp).
 *
 * Pure function: no I/O, no clock, no time-decay, no engagement bonus, no mutation.
 * Same outcomes always produce the same result.
 *
 * XP is derived ONLY from the honesty contract (blueprint §2):
 *   work orders done, phases completed, releases, green test runs, weekly streak.
 *
 * Forbidden (never contributes XP):
 *   - App opens, navigation, page views, messages, file reads/writes.
 *   - Daily-reset streaks (only weekly, capped).
 *
 * Honest zero state: when all outcome counts are zero, xp = 0, pctToNext = 0,
 * level = 1, title = RANKS[0].title. The bar is NEVER artificially inflated.
 */
export function computeGuildLevel(outcomes: GuildOutcomes): GuildLevel {
  // ── XP derivation (honesty contract) ──────────────────────────────────────
  const cappedStreak = Math.min(
    Math.max(0, Math.trunc(outcomes.weeklyStreak ?? 0)),
    MAX_STREAK_WEEKS,
  );

  const xp =
    outcomes.workOrdersDone * XP_PER_WO +
    outcomes.phasesCompleted * XP_PER_PHASE +
    outcomes.releases * XP_PER_RELEASE +
    outcomes.greenTestRuns * XP_PER_GREEN_TEST +
    cappedStreak * XP_PER_STREAK_WEEK;

  // ── Granular level + rank band ──────────────────────────────────────────────
  // The level climbs with XP; the rank is the BAND the level falls into (the last
  // rank whose minLevel ≤ level). Level ≠ rank (a rank spans several levels).
  const level = levelForXp(xp);
  const rankIndex = rankForLevel(level);
  // biome-ignore lint/style/noNonNullAssertion: RANKS is non-empty (40 ranks, verified by tests)
  const currentRank = RANKS[rankIndex]!;

  // ── Progress to the NEXT granular level (the hero/header bar) ────────────────
  const curLevelXp = xpForLevel(level);
  const nextLevelXp = xpForLevel(level + 1);
  const span = nextLevelXp - curLevelXp;
  const pctToNext =
    span > 0 ? Math.min(100, Math.max(0, Math.floor(((xp - curLevelXp) / span) * 100))) : 0;

  return {
    level,
    rankIndex,
    title: currentRank.title,
    titleEn: currentRank.titleEn,
    icon: currentRank.icon,
    sprite: currentRank.sprite,
    grade: currentRank.grade,
    xp,
    next: nextLevelXp,
    pctToNext,
  };
}

/**
 * The four celebration tiers (plus "none"), ordered by scale.
 *
 *   "toast"   — work order closed (green tests, achievement + workOrder)
 *   "phase"   — phase completed (phase transition or phase-scoped end/handoff)
 *   "release" — project released / reached the launched "release" phase
 *   "levelup" — guild or agent crossed a level threshold
 *   "none"    — no celebration (activity events, unknown, failure, ambiguous)
 */
export type CelebrationTier = "toast" | "phase" | "release" | "levelup" | "none";

/**
 * Classify an event from the dashboard stream into a celebration tier.
 *
 * Pure function: same input always yields same output; no side effects; event is never mutated.
 *
 * Decision table (FRD-09 blueprint §2 + AC-09-005.*):
 *
 * | event         | conditions                          | tier     |
 * |---------------|-------------------------------------|----------|
 * | achievement   | task = "levelup" or "level-up"      | levelup  |
 * | achievement   | task = "release"                    | release  |
 * | achievement   | task starts with "phase:"           | phase    |
 * | achievement   | workOrder present, status ≠ "fail"  | toast    |
 * | test_ok       | workOrder present                   | toast    |
 * | end           | task = "release"                    | release  |
 * | end           | task starts with "phase:"           | phase    |
 * | handoff       | task starts with "phase:"           | phase    |
 * | (anything)    | status = "fail"                     | none     |
 * | (anything)    | unknown / activity                  | none     |
 *
 * Ethical invariant (FRD-09): activity events (read, write, edit, message, start, review,
 * blocked, test_fail, navigation, app-open) ALWAYS return "none".
 */
export function classifyCelebration(event: Event): CelebrationTier {
  // Failure is never a celebration (FRD-09 ethical constraint).
  if (event.status === "fail") {
    return "none";
  }

  const { event: kind, task, workOrder } = event;

  // ── achievement events (the primary verifiable-result signal) ──────────────
  if (kind === "achievement") {
    return _classifyAchievement(task, workOrder);
  }

  // ── test_ok: green test suite with a work-order attribution ───────────────
  if (kind === "test_ok") {
    // test_ok without a work-order is ambiguous (could be a standalone run).
    return _hasWorkOrder(workOrder) ? "toast" : "none";
  }

  // ── end / handoff: phase-scoped transitions ────────────────────────────────
  if (kind === "end" || kind === "handoff") {
    return _classifyPhaseScoped(task);
  }

  // ── everything else: activity events (read, write, edit, message, start,
  //    review, blocked, test_fail, navigation, app-open, unknown) ─────────────
  return "none";
}

/** True when `workOrder` is a non-empty string. */
function _hasWorkOrder(workOrder: unknown): boolean {
  return typeof workOrder === "string" && workOrder.length > 0;
}

/** Classify an "achievement" event. Behavior copied verbatim from the inline block. */
function _classifyAchievement(task: unknown, workOrder: unknown): CelebrationTier {
  // Level-up crossing takes priority over everything else.
  if (task === "levelup" || task === "level-up") {
    return "levelup";
  }
  // Release / launch (reached the launched "release" phase).
  if (task === "release") {
    return "release";
  }
  // Phase completion (e.g. "phase:design", "phase:architecture").
  if (typeof task === "string" && task.startsWith("phase:")) {
    return "phase";
  }
  // Work-order closed (the most common verifiable result).
  if (_hasWorkOrder(workOrder)) {
    return "toast";
  }
  // achievement with no meaningful context → ambiguous → none.
  return "none";
}

/** Classify an end/handoff event by its phase scope. Behavior copied verbatim. */
function _classifyPhaseScoped(task: unknown): CelebrationTier {
  if (task === "release") {
    return "release";
  }
  if (typeof task === "string" && task.startsWith("phase:")) {
    return "phase";
  }
  // end/handoff without a phase scope is not a verifiable result.
  return "none";
}

// ---------------------------------------------------------------------------
// deriveGuildOutcomes — aggregate real outcomes from portfolio statuses + events (WO-09-004)
//
// Pure derivation layer: takes already-read data and produces GuildOutcomes.
// No I/O — the caller (Server Component in app/layout.tsx) reads the data;
// this function only processes what it receives (architecture §6: data layer
// boundary is lib/, components never touch fs directly).
// ---------------------------------------------------------------------------

/**
 * Input for deriveGuildOutcomes: the already-read statuses for every portfolio project
 * and the events snapshot (for green test runs).
 */
export type GuildOutcomesInput = {
  /** StatusResult for each portfolio project (read via readStatus). */
  statuses: readonly StatusResult[];
  /**
   * Events snapshot from readEvents() (for greenTestRuns count).
   * May be omitted (treated as zero test runs).
   */
  eventsSnapshot?: EventsSnapshot | null;
  /**
   * Current weekly streak (weeks with at least one closed WO).
   * Optional — 0 when not tracked yet.
   */
  weeklyStreak?: number;
};

/**
 * Derive GuildOutcomes from the portfolio's real data (WO-09-004, AC-09-004.1).
 *
 * Honesty contract (blueprint §2):
 *   - workOrdersDone  = sum of status.workOrdersDone across all projects (present + valid)
 *   - phasesCompleted = count of projects whose phase is in { design, architecture, implementation,
 *                       release } (each project that advanced past product = 1 phase)
 *   - releases        = count of projects in the launched "release" phase (reached launch)
 *   - greenTestRuns   = count of "test_ok" events in the snapshot
 *
 * All missing/malformed statuses are skipped (never throws, fail-soft).
 * Never inflates XP — strictly derived from verifiable outcomes.
 *
 * Pure function: no I/O, no side-effects, same input → same output.
 */
export function deriveGuildOutcomes(input: GuildOutcomesInput): GuildOutcomes {
  const { statuses, eventsSnapshot, weeklyStreak } = input;

  let workOrdersDone = 0;
  let phasesCompleted = 0;
  let releases = 0;

  for (const sr of statuses) {
    const tally = _tallyStatus(sr);
    workOrdersDone += tally.workOrdersDone;
    phasesCompleted += tally.phasesCompleted;
    releases += tally.releases;
  }

  return {
    workOrdersDone,
    phasesCompleted,
    releases,
    greenTestRuns: _countGreenTestRuns(eventsSnapshot),
    weeklyStreak: weeklyStreak ?? 0,
  };
}

/** Phases that count as advanced past "product" (one phaseCompleted each). */
const COMPLETED_PHASES = new Set(["design", "architecture", "implementation", "release"]);

/**
 * Per-project contribution to the guild outcomes. Behavior copied verbatim from
 * the original inline loop body (fail-soft: absent/null status → all zeros).
 */
function _tallyStatus(sr: StatusResult): {
  workOrdersDone: number;
  phasesCompleted: number;
  releases: number;
} {
  if (!sr.present || sr.status === null) {
    return { workOrdersDone: 0, phasesCompleted: 0, releases: 0 };
  }
  const st = sr.status;

  // workOrdersDone: accumulate per-project WOs closed
  const workOrdersDone =
    typeof st.workOrdersDone === "number" && Number.isFinite(st.workOrdersDone)
      ? Math.max(0, Math.trunc(st.workOrdersDone))
      : 0;

  // phasesCompleted: project advanced beyond "product" phase
  const phasesCompleted = typeof st.phase === "string" && COMPLETED_PHASES.has(st.phase) ? 1 : 0;

  // releases: project reached the launched "release" phase (DR-085)
  const releases = st.phase === "release" ? 1 : 0;

  return { workOrdersDone, phasesCompleted, releases };
}

/** Count "test_ok" events in the snapshot (0 when absent). Behavior copied verbatim. */
function _countGreenTestRuns(eventsSnapshot: EventsSnapshot | null | undefined): number {
  if (!eventsSnapshot) return 0;
  let greenTestRuns = 0;
  for (const ev of eventsSnapshot.events) {
    if (ev.event === "test_ok") {
      greenTestRuns += 1;
    }
  }
  return greenTestRuns;
}
